---
- name: include_tasks tune_kernel_parameters.yml
  include_tasks: tune_kernel_parameters.yml
  when:
    - ansible_os_family == 'RedHat'
    - tune_kernel_parameters
  tags: tune_kernel_parameters

- name: include_tasks configure_firewall.yml
  include_tasks: configure_firewall.yml
  when:
    - configure_firewall
    - ansible_os_family in ['RedHat', 'Suse']
  tags: configure_firewall

- name: include_tasks setup_ntp.yml
  include_tasks: setup_ntp.yml
  when: ntp_service_enabled
  tags: configure_ntp
